env:
  node: true
parser: 'babel-eslint'
extends: airbnb
plugins:
  - react
  - jsx-a11y
  - import
rules:
  "import/no-extraneous-dependencies": ["error", { "devDependencies": ["webpack.config.*.js", "gulpfile.babel.js"] }]
  "react/require-default-props": 0
  "react/no-unused-prop-types": 0
